language: node_js
node_js:
  - '8'
install:
  - npm install
before_deploy: npm run build
deploy:
  provider: bintray
  file: bintray.json
  user: mogoodrich
  key: $BINTRAY_API_KEY
  dry-run: false
  on:
    tags: true
